### ISSUE TITLE
Errors are rendered as plain text even when requesting JSON

### ISSUE THREAD

**Issue by marcban** [zandero/rest.vertx#1]
When there are exceptions raised by the body handler (for example JSON description not conform to the body type), they are rendered as plain text, not JSON, although the content-type is `application/json` as expected

it would be interesting to have a way to customize the output for exceptions.

(tested on 0.2 - Great project by the way!)

**Comment by drejc** [comment]
Thanks for reporting.
Could you provide a unit test, showing the behaviour, so I can fix it.
Just fork and create a pull request or send me a patch.

**Comment by marcban** [comment]
to be short, the line that write the response is in RestRouter.java, line 266:

 `response.setStatusCode(exception.getStatusCode()).end(exception.getMessage());`

so it seems on purpose. In my case I would like a result like `{"status:"ERROR","message":"the exception message"}` but may be that's not the case for everyone

A way to let the user choose his own format for exceptions response  would be to call a global handler provided when initializing the routes.

**Comment by drejc** [comment]
Will look into it, probably a global Rest error handler / message writer is
the best solution. Then you can hook up your own writer to handle edge
cases like this.

**Comment by marcban** [comment]
thank you. I think this project is very a good answer for quickly developing rest API with VertX !

**Comment by drejc** [comment]
# Error handling
Unhandled exceptions can be addressed via a designated _ExceptionHandler_:
1. for a given method path
1. for a given root path
1. globally assigned to the RestRouter

If no designated exception handler is provided, a default exception handler kick 
in using the response type writer associated with the given method.

## Path / Method error handler
Both class and methods support **@CatchWith** annotation.  

**@CatchWith** annotation must provide an _ExceptionHandler_ implementation that handles the thrown exception: 

```java
@GET
@Path("/test")
@CatchWith(MyExceptionHandler.class)
public String fail() {

    throw new IllegalArgumentExcetion("Bang!"); 
}
```
```java
public class MyExceptionHandler implements ExceptionHandler {
    @Override
    public void handle(Throwable cause, HttpResponseWriter writer, RoutingContext context) {

        context.response().setStatusCode(406);
        writer.write("I got this ... : '" + cause.getMessage() + "'", context.request(), context.response());
    }
}
```

By default the _ExceptionHandler_ is provided with a writer that normally would be associated with a given method.  
If desired a designated writer can be defined:

```java
@GET
@Path("/test")
@CatchWith(value = MyExceptionHandler.class, writer = MyExceptionWriter.class)
public String fail() {

    throw new IllegalArgumentExcetion("Bang!"); 
}
```

## Global error handler
The global error handler is invoked in case no path or method error handler is provided.  
In case no global error handler is associated a default (generic) error handler is invoked.

```java
    Router router = RestRouter.register(vertx, handled, unhandled);
    RestRouter.errorHandler(MyExceptionHandler.class);  
    
    // OR ALTERNATIVELY
    RestRouter.errorHandler(MyExceptionHandler.class, MyExceptionWriter.class);
    
    vertx.createHttpServer()
        .requestHandler(router::accept)
        .listen(PORT);
```

Available since version 0.3 ...

**Comment by marcban** [comment]
...thanks a lot!

**Comment by drejc** [comment]
No problem ... this part was completely missing. 
Maybe a way to bind handlers to certain response codes ... aka a 404 handler, 406 handler would be a handy solution. Maybe in the next iteration.
